version: "3.8"

networks:
  elastic:
    driver: bridge

services:
  elasticsearch:
    container_name: es_ojt_elasticsearch
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    environment:
      node.name: es01
      cluster.name: es-docker-cluster
      discovery.type: single-node
      bootstrap.memory_lock: true
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
    volumes:
      - /mnt/disks/data/qa42/esojt:/usr/share/elasticsearch/data
    ports:
      - "14280:9200"
      - "14281:9300"
    networks:
      - elastic

  kibana:
    container_name: es_ojt_kibana
    image: docker.elastic.co/kibana/kibana:7.16.3
    environment:
      elasticsearch.hosts: "http://elasticsearch:14280"
      elasticsearch.username: es_ojt
    ports:
      - "14282:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch
